plugins:
  - jekyll-remote-theme
remote_theme: mmistakes/so-simple-theme
logo: "images/mni152.png"
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
