plugins:
  - jekyll-remote-theme
remote_theme: mmistakes/so-simple-theme

locale: en-US
title: "UT College Life Study"
description: "A longitudinal study of undergraduate students UT Austin."
baseurl: "/college-life-study"
url: https://collegelife.utbrainstudy.org

sass:
  sass_dir: _sass
  style: compressed
  
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"

